# This is a basic workflow to help you get started with Actions

name: Deploy_app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.*
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test
      - name: Publish
        run: dotnet publish ./MWO6/MWO6.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: personsApi-artifact
          path: ${{ env.DOTNET_ROOT}}/api
          
  deploy-dev:
        runs-on: ubuntu-latest
        needs: build
        environment:
          name: 'Dev'
          url: ${{ https://mwo6.azurewebsites.net }}
        steps:
          - name: Download Build
            uses: actions/download-artifact@3.0.0
            with:
              name: personsApi-artifact
          - name: Azure WebApp
            id: deploy-to-azure
            uses: Azure/webapps-deploy@v2
            with:
              app-name: 'personsApi-dev'
              publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
              
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: 
      name: 'Prod'
      url:  ${{ https://mwo6.azurewebsites.net }}
    steps:
      - name: Download Build
        uses: actions/download-artifact@v3.0.0
        with:
          name: personsApi-artifact
      - name: Azure Webapp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'MWO6'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
          
